## Numpy

In [ ]:
import numpy as np

### Basic exercises

####  Ceate a 1D array of numbers from 0 to 9

In [9]:
# Solution
# 1. Create a 1D array of numbers from 0 to 9
arr_1d = np.arange(10)
arr_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Create a 3×3 numpy array of all True’s

In [10]:
# Solution
true_array = np.ones((3, 3), dtype=bool)
true_array

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

#### Replace all odd numbers in arr with -1

In [11]:
# Input
arr = np.arange(10)

# Solution
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

#### Convert a 1D array to a 2D array with 2 rows

In [12]:
# Input
arr = np.arange(10)
print(arr)

# Solution
arr_2d = arr.reshape(2, -1)
arr_2d

[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### Stack arrays a and b vertically and then horizontally

In [13]:
# Input
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)

print("vertically stacked arrays:")
# Solution
vert_stack = np.vstack((a, b))
print(vert_stack)

print("horizontally stacked arrays:")
# Solution
horiz_stack = np.hstack((a, b))
print(horiz_stack)


vertically stacked arrays:
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
horizontally stacked arrays:
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


#### Find positions where elements of a and b match

In [14]:
# Input
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

# Solution
matches = np.where(a == b)
print("Matching indices:", matches)
print("Matching indices:", matches[0])

Matching indices: (array([1, 3, 5, 7]),)
Matching indices: [1 3 5 7]


####  Get all items between 5 and 10 from a

In [15]:
# Input
a = np.arange(15)

# Solutions
items = a[(a >= 5) & (a <= 10)]
print("Items between 5 and 10:", items)


Items between 5 and 10: [ 5  6  7  8  9 10]


#### Get the positions of top 5 maximum values in a given array a

In [16]:
# Input
np.random.seed(100)
a = np.random.uniform(1, 50, 20)
print(a)

# Solution:
top_5_pos = np.argsort(a)[-5:][::-1]
print("Indices of the top 5 largest values:", top_5_pos)
top_5_values = a[top_5_pos]
print("Top 5 largest values:", top_5_values)

[27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361]
Indices of the top 5 largest values: [15 10  3  7 18]
Top 5 largest values: [48.95256545 44.67477576 42.39403048 41.466785   40.99501269]


#### Compute the min-by-max (i.e. min/max) for each row for given 2d numpy array (see [apply_along_axis](https://numpy.org/doc/stable/reference/generated/numpy.apply_along_axis.html#numpy-apply-along-axis))

In [17]:
# Input
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print(a)

# Solution
min_by_max = np.apply_along_axis(lambda x: np.min(x) / np.max(x), arr=a, axis=1)
print("Min by max for each row:", min_by_max)

[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]
Min by max for each row: [0.44444444 0.125      0.5        1.         0.11111111]


####  Find the duplicate entries in the given numpy array and mark them as True. First time occurrences should be False.

In [18]:
# Input
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print('Array: ', a)

# Solution
duplicates = np.full(a.shape, True)
unique_positions = np.unique(a, return_index=True)[1]
print('Unique positions:', unique_positions)
duplicates[unique_positions] = False
print('Duplicate positions:', np.where(duplicates)[0])

Array:  [0 0 3 0 2 4 2 2 2 2]
Unique positions: [0 4 2 5]
Duplicate positions: [1 3 6 7 8 9]


#### Find the index of 5th repetition of number 1 in x
Make use of numpy.where

In [21]:
# Input
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
n = 5
# Soluzione
index_5th_1 = np.where(x == 1)[0][4]
print("Index of the 5th occurrence of 1:", index_5th_1)

Index of the 5th occurrence of 1: 8


#### Compute the moving average of window size 3, for the given 1D array
Make use of numpy.convolve

In [20]:
# Input
arr = np.array([8, 8, 3, 7, 7, 0, 4, 2, 5, 2])

# Solution
moving_avg = np.convolve(arr, np.ones(3)/3, mode='valid')
print("Moving average with window size 3:", moving_avg)

Moving average with window size 3: [6.33333333 6.         5.66666667 4.66666667 3.66666667 2.
 3.66666667 3.        ]


### Iris dataset

#### Import the iris dataset from iris.txt
See np.genfromtxt, load the dataset with dtype=np.str

In [22]:
from google.colab import drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [25]:
# Input filepath
#FILEPATH = [...]
# Soultion
FILEPATH = "/content/drive/MyDrive/MLinAPP_Data/iris.txt"
iris = np.genfromtxt(FILEPATH, delimiter=',', dtype='str')
iris[:3]

array([['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.0', '1.4', '0.2', 'Iris-setosa'],
       ['4.7', '3.2', '1.3', '0.2', 'Iris-setosa']], dtype='<U15')

#### Print the unique labels of the dataset

In [28]:
# Solution
unique_labels = np.unique(iris[:, 4])
print("Unique labels:", unique_labels)


Unique labels: ['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


#### Find how many samples (i.e. rows) we have for each unique label

In [34]:
# Solution
labels, counts = np.unique(iris[:, 4], return_counts=True)
label_counts = dict(zip(labels, counts))
print("Label counts:", label_counts)

Label counts: {np.str_('Iris-setosa'): np.int64(50), np.str_('Iris-versicolor'): np.int64(50), np.str_('Iris-virginica'): np.int64(50)}


#### Find the mean, median, standard deviation of iris's sepallength (1st column)
See np.genfromtxt, load only the 1st column with the appropiate data type

In [36]:
# Solution
sepallength = np.genfromtxt(FILEPATH, delimiter=',', dtype='float', usecols=[0])
mean_sl, med_sl, std_sl = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print("Mean:", mean_sl)
print("Median:", med_sl)
print("Standard deviation:", std_sl)

Mean: 5.843333333333334
Median: 5.8
Standard deviation: 0.8253012917851409


####  Find the mean, median, standard deviation of iris's sepallength (1st column) for each unique labels

In [40]:
# Solution
for label in np.unique(iris[:, 4]):
    mask = iris[:, 4] == label
    sl_filtered = sepallength[mask]
    print("just show 10 of recordes:", sl_filtered[:10])
    print(f"{label}: Mean={np.mean(sl_filtered):.2f}, Median={np.median(sl_filtered):.2f}, Std={np.std(sl_filtered):.2f}")

just show 10 of recordes: [5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9]
Iris-setosa: Mean=5.01, Median=5.00, Std=0.35
just show 10 of recordes: [7.  6.4 6.9 5.5 6.5 5.7 6.3 4.9 6.6 5.2]
Iris-versicolor: Mean=5.94, Median=5.90, Std=0.51
just show 10 of recordes: [6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3 6.7 7.2]
Iris-virginica: Mean=6.59, Median=6.50, Std=0.63


####  Create a new column for volume in iris, where volume is (pi x petallength x sepal_length^2)/3

In [41]:
# Solution
# Create a new column for volume in iris, where volume is (pi x petallength x sepal_length^2)/3
sepallength = iris[:, 0].astype('float')
petallength = iris[:, 2].astype('float')
volume = (np.pi * petallength * (sepallength ** 2)) / 3
volume = volume[:, np.newaxis] # Reshape to a column vector
iris_with_volume = np.hstack([iris, volume])
iris_with_volume[:3]

array([['5.1', '3.5', '1.4', '0.2', 'Iris-setosa', '38.13265162927291'],
       ['4.9', '3.0', '1.4', '0.2', 'Iris-setosa', '35.200498485922445'],
       ['4.7', '3.2', '1.3', '0.2', 'Iris-setosa', '30.0723720777127']],
      dtype='<U32')

#### Randomly sample iris's species such that setosa is twice the number of versicolor and virginica
See [numpy.random.choice](https://numpy.org/doc/stable/reference/random/generated/numpy.random.choice.html#numpy-random-choice)

In [44]:
# (Probabilities: setosa=0.5, versicolor=0.25, virginica=0.25)
sampled_species = np.random.choice(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], size=150, p=[0.5, 0.25, 0.25])
print(sampled_species[:20])

['Iris-virginica' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'
 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica']


#### Sort the iris dataset based on sepallength column

In [47]:
# Solution
sorted_iris = iris[iris[:, 0].astype('float').argsort()]
print(sorted_iris[:20])

[['4.3' '3.0' '1.1' '0.1' 'Iris-setosa']
 ['4.4' '2.9' '1.4' '0.2' 'Iris-setosa']
 ['4.4' '3.2' '1.3' '0.2' 'Iris-setosa']
 ['4.4' '3.0' '1.3' '0.2' 'Iris-setosa']
 ['4.5' '2.3' '1.3' '0.3' 'Iris-setosa']
 ['4.6' '3.6' '1.0' '0.2' 'Iris-setosa']
 ['4.6' '3.1' '1.5' '0.2' 'Iris-setosa']
 ['4.6' '3.4' '1.4' '0.3' 'Iris-setosa']
 ['4.6' '3.2' '1.4' '0.2' 'Iris-setosa']
 ['4.7' '3.2' '1.3' '0.2' 'Iris-setosa']
 ['4.7' '3.2' '1.6' '0.2' 'Iris-setosa']
 ['4.8' '3.0' '1.4' '0.3' 'Iris-setosa']
 ['4.8' '3.1' '1.6' '0.2' 'Iris-setosa']
 ['4.8' '3.4' '1.9' '0.2' 'Iris-setosa']
 ['4.8' '3.4' '1.6' '0.2' 'Iris-setosa']
 ['4.8' '3.0' '1.4' '0.1' 'Iris-setosa']
 ['4.9' '2.4' '3.3' '1.0' 'Iris-versicolor']
 ['4.9' '3.1' '1.5' '0.1' 'Iris-setosa']
 ['4.9' '3.1' '1.5' '0.1' 'Iris-setosa']
 ['4.9' '3.0' '1.4' '0.2' 'Iris-setosa']]


#### Find the most frequent value of petal length (3rd column) in iris dataset

In [51]:
# Solution
vals, counts = np.unique(iris[:, 2], return_counts=True)
most_frequent_petal_length = vals[np.argmax(counts)]
print("most_frequent_petal_length ", most_frequent_petal_length)

most_frequent_petal_length  1.5


#### Find the position of the first occurrence of a value greater than 1.0 in petalwidth 4th column of iris dataset

see [np.argwhere](https://numpy.org/doc/stable/reference/generated/numpy.argwhere.html#numpy-argwhere)

In [53]:
# Solution
first_pos = np.argwhere(iris[:, 3].astype('float') > 1.0)[0][0]
print("Position of the first occurrence of a value greater than 1.0 in petalwidth:", first_pos)

Position of the first occurrence of a value greater than 1.0 in petalwidth: 50


#### Get the rows having petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [56]:
# Solution
condition = (iris[:, 2].astype('float') > 1.5) & (iris[:, 0].astype('float') < 5.0)
filtered_rows = iris[condition]
print("petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0 \n", filtered_rows[:10])

petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0 
 [['4.8' '3.4' '1.6' '0.2' 'Iris-setosa']
 ['4.8' '3.4' '1.9' '0.2' 'Iris-setosa']
 ['4.7' '3.2' '1.6' '0.2' 'Iris-setosa']
 ['4.8' '3.1' '1.6' '0.2' 'Iris-setosa']
 ['4.9' '2.4' '3.3' '1.0' 'Iris-versicolor']
 ['4.9' '2.5' '4.5' '1.7' 'Iris-virginica']]
